#!/bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 10 

bspc config border_width         2
bspc config window_gap           2

bspc config split_ratio          0.52
bspc config focus_follows_pointer  true
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config automatic_scheme     spiral

bspc rule -a Zathura state=tiled
bspc rule -a Inkscape state=tiled
bspc rule -a Seamonkey desktop='^2'
